# General
site_name: Pretzel
copyright: 'Copyright © iwoithe 2020 <br> Creative Commons Attribution-ShareAlike 4.0 International'

# Gitlab Repository
#repo_url: 'https://gitlab.com/iwoithe/pretzel'

theme: readthedocs

# Overide the default navigation
nav:
  - 'Welcome to Pretzel': 'index.md'

# Markdown Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed

  - pymdownx.highlight:
      linenums: true


# Plugins
plugins:
  - search
#  - mermaid2
